ci: stop the pulsar service forcefully (#410)
**Motivation**

I found that CI always failed, the following is CI log:
```
--- Stop the pulsar service ---
doing stop standalone ...
stopping standalone
Shutdown is in progress... Please wait...
...........
Shutdown is in progress... Please wait...
Thread dumps are taken for analysis at /pulsar/logs/standalone.out
WARNNING :  standalone is not stopped completely.
Error: Process completed with exit code 1.
````
so I add `-force` to `bin/pulsar-daemon stop standalone` for stop the pulsar service forcefully.

(cherry picked from commit 36d229726779752179ed84e97e668b78287f69e5)