fix: Fix TestUpdateTopicNotExist and TestUpdateNonPartitionedTopic (#1067)
### Motivation

There is two failed tests when using Pulsar 3.0.0:
```
=== RUN   TestUpdateTopicNotExist
    update_test.go:85: 
        	Error Trace:	/pulsarctl/pkg/ctl/topic/update_test.go:85
        	Error:      	Not equal: 
        	            	expected: "code: 409 reason: Topic is not partitioned topic"
        	            	actual  : "code: 409 reason: Topic persistent://public/default/non-exist-topic is not the partitioned topic."
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-code: 409 reason: Topic is not partitioned topic
        	            	+code: 409 reason: Topic persistent://public/default/non-exist-topic is not the partitioned topic.
        	Test:       	TestUpdateTopicNotExist
--- FAIL: TestUpdateTopicNotExist (0.01s)
=== RUN   TestUpdateNonPartitionedTopic
    update_test.go:96: 
        	Error Trace:	/pulsarctl/pkg/ctl/topic/update_test.go:96
        	Error:      	Not equal: 
        	            	expected: "code: 409 reason: Topic is not partitioned topic"
        	            	actual  : "code: 409 reason: Topic persistent://public/default/test-update-non-partitioned-topic is not the partitioned topic."
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-code: 409 reason: Topic is not partitioned topic
        	            	+code: 409 reason: Topic persistent://public/default/test-update-non-partitioned-topic is not the partitioned topic.
        	Test:       	TestUpdateNonPartitionedTopic
--- FAIL: TestUpdateNonPartitionedTopic (0.02s)
```

More details in https://github.com/streamnative/pulsarctl/actions/runs/4976702208/jobs/8905382299?pr=1064#step:3:1349

This is because we change the log message in Pulsar 3.0.0 by this PR: https://github.com/apache/pulsar/pull/19166

### Modifications

* Fix the assert of the test